# app.yaml

runtime: nodejs12

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /(.*)$
    static_files: build/\1
    upload: build/(.*)

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto